// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: protobuf/account_query.proto

package account_query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountQueryServiceClient is the client API for AccountQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountQueryServiceClient interface {
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type accountQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountQueryServiceClient(cc grpc.ClientConnInterface) AccountQueryServiceClient {
	return &accountQueryServiceClient{cc}
}

func (c *accountQueryServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/protobuf.AccountQueryService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountQueryServiceServer is the server API for AccountQueryService service.
// All implementations must embed UnimplementedAccountQueryServiceServer
// for forward compatibility
type AccountQueryServiceServer interface {
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	mustEmbedUnimplementedAccountQueryServiceServer()
}

// UnimplementedAccountQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountQueryServiceServer struct {
}

func (UnimplementedAccountQueryServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedAccountQueryServiceServer) mustEmbedUnimplementedAccountQueryServiceServer() {}

// UnsafeAccountQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountQueryServiceServer will
// result in compilation errors.
type UnsafeAccountQueryServiceServer interface {
	mustEmbedUnimplementedAccountQueryServiceServer()
}

func RegisterAccountQueryServiceServer(s grpc.ServiceRegistrar, srv AccountQueryServiceServer) {
	s.RegisterService(&AccountQueryService_ServiceDesc, srv)
}

func _AccountQueryService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountQueryServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.AccountQueryService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountQueryServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountQueryService_ServiceDesc is the grpc.ServiceDesc for AccountQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.AccountQueryService",
	HandlerType: (*AccountQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _AccountQueryService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/account_query.proto",
}
