// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nidhey27/cqrs-go/ent/account"
	"github.com/nidhey27/cqrs-go/ent/predicate"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetAccountNumber sets the "account_number" field.
func (au *AccountUpdate) SetAccountNumber(s string) *AccountUpdate {
	au.mutation.SetAccountNumber(s)
	return au
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (au *AccountUpdate) SetNillableAccountNumber(s *string) *AccountUpdate {
	if s != nil {
		au.SetAccountNumber(*s)
	}
	return au
}

// SetAccountHolderName sets the "account_holder_name" field.
func (au *AccountUpdate) SetAccountHolderName(s string) *AccountUpdate {
	au.mutation.SetAccountHolderName(s)
	return au
}

// SetNillableAccountHolderName sets the "account_holder_name" field if the given value is not nil.
func (au *AccountUpdate) SetNillableAccountHolderName(s *string) *AccountUpdate {
	if s != nil {
		au.SetAccountHolderName(*s)
	}
	return au
}

// SetAccountBalance sets the "account_balance" field.
func (au *AccountUpdate) SetAccountBalance(f float64) *AccountUpdate {
	au.mutation.ResetAccountBalance()
	au.mutation.SetAccountBalance(f)
	return au
}

// SetNillableAccountBalance sets the "account_balance" field if the given value is not nil.
func (au *AccountUpdate) SetNillableAccountBalance(f *float64) *AccountUpdate {
	if f != nil {
		au.SetAccountBalance(*f)
	}
	return au
}

// AddAccountBalance adds f to the "account_balance" field.
func (au *AccountUpdate) AddAccountBalance(f float64) *AccountUpdate {
	au.mutation.AddAccountBalance(f)
	return au
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.AccountNumber(); ok {
		_spec.SetField(account.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := au.mutation.AccountHolderName(); ok {
		_spec.SetField(account.FieldAccountHolderName, field.TypeString, value)
	}
	if value, ok := au.mutation.AccountBalance(); ok {
		_spec.SetField(account.FieldAccountBalance, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.AddedAccountBalance(); ok {
		_spec.AddField(account.FieldAccountBalance, field.TypeFloat64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetAccountNumber sets the "account_number" field.
func (auo *AccountUpdateOne) SetAccountNumber(s string) *AccountUpdateOne {
	auo.mutation.SetAccountNumber(s)
	return auo
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableAccountNumber(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetAccountNumber(*s)
	}
	return auo
}

// SetAccountHolderName sets the "account_holder_name" field.
func (auo *AccountUpdateOne) SetAccountHolderName(s string) *AccountUpdateOne {
	auo.mutation.SetAccountHolderName(s)
	return auo
}

// SetNillableAccountHolderName sets the "account_holder_name" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableAccountHolderName(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetAccountHolderName(*s)
	}
	return auo
}

// SetAccountBalance sets the "account_balance" field.
func (auo *AccountUpdateOne) SetAccountBalance(f float64) *AccountUpdateOne {
	auo.mutation.ResetAccountBalance()
	auo.mutation.SetAccountBalance(f)
	return auo
}

// SetNillableAccountBalance sets the "account_balance" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableAccountBalance(f *float64) *AccountUpdateOne {
	if f != nil {
		auo.SetAccountBalance(*f)
	}
	return auo
}

// AddAccountBalance adds f to the "account_balance" field.
func (auo *AccountUpdateOne) AddAccountBalance(f float64) *AccountUpdateOne {
	auo.mutation.AddAccountBalance(f)
	return auo
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (auo *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.AccountNumber(); ok {
		_spec.SetField(account.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := auo.mutation.AccountHolderName(); ok {
		_spec.SetField(account.FieldAccountHolderName, field.TypeString, value)
	}
	if value, ok := auo.mutation.AccountBalance(); ok {
		_spec.SetField(account.FieldAccountBalance, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.AddedAccountBalance(); ok {
		_spec.AddField(account.FieldAccountBalance, field.TypeFloat64, value)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
